apiVersion: v1
kind: Service
metadata:
  name: opsnova-backend
spec:
  selector:
    app: opsnova-backend
  ports:
    - port: 8000
      targetPort: 8000
  type: {{ .Values.service.backend.type }}
---
apiVersion: v1
kind: Service
metadata:
  name: opsnova-frontend
spec:
  selector:
    app: opsnova-frontend
  ports:
    - port: 80
      targetPort: 80
  type: {{ .Values.service.frontend.type }}
